#!/usr/bin/perl

use strict;
use warnings;

sub build_template {
  my $template = shift or die;
  my $out_path = shift or die;
  my $insertions_ref = shift or die;
  my %insertions = %$insertions_ref;

  open my $out, '>', $out_path or die;
  $template =~ s/\{\{\s(\w+)\s\}\}/$insertions{$1}/g;
  print $out $template;
  close $out;
}

local $/;

my $doc_content = `cat DOC.md`;
my $dc = './src/doc-codes';
my %snippets = (
  'state_doc' => `cat $dc/state-doc.ts`,
  'signal_doc' => `cat $dc/signal-doc.ts`,
);
build_template($doc_content, 'DOC2.md', \%snippets);

my $doc_html = `pandoc DOC2.md`;
my %index = (
  'doc' => $doc_html,
);
my $index_template = `cat index.template.html`;
build_template($index_template, 'index.html', \%index);

system "rm DOC2.md";
